spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - 13.231.124.138:9094
          auto-create-topics: false
      bindings:
        sampleConsumer-in-0:
          destination: sample-topic
      instance-count: 1