spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - sample-cluster-kafka-bootstrap.kafka
          auto-create-topics: false
      bindings:
        sampleConsumer-in-0:
          destination: sample-topic
      instance-count: 1