apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-mesh-app-service2-clusterrole
  namespace: istio-network
  labels:
    app: service-mesh-app-service2
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
