apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-prometheus
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - prometheus-ingressgateway
  http:
    - match:
        - uri:
            prefix: /prometheus
      route:
        - destination:
            host: prometheus
            port:
              number: 9090
---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: virtual-service-graph
#  namespace: istio-system
#spec:
#  hosts:
#    - "*"
#  gateways:
#    - prometheus-ingressgateway
#  http:
#    - match:
#        - uri:
#            prefix: /graph
#      route:
#        - destination:
#            host: prometheus
#            port:
#              number: 9090
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: virtual-service-metrics
#  namespace: istio-system
#spec:
#  hosts:
#    - "*"
#  gateways:
#    - prometheus-ingressgateway
#  http:
#    - match:
#        - uri:
#            prefix: /metrics
#      route:
#        - destination:
#            host: prometheus
#            port:
#              number: 9090