apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service1
  namespace: istio-network
spec:
  hosts:
    - "*"
  gateways:
    - service-mesh-ingressgateway
  http:
    - match:
        - uri:
            prefix: /service1
      route:
        - destination:
            host: service-mesh-app-service1
            port:
              number: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service2
  namespace: istio-network
spec:
  hosts:
    - "*"
  gateways:
    - service-mesh-ingressgateway
  http:
    - match:
        - uri:
            prefix: /service2
      route:
        - destination:
            host: service-mesh-app-service2
            port:
              number: 8080