# Default values for istio-microk8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

istio-init:
  enabled: false

istio-base:
  enabled: false

istiod:
  enabled: false
  meshConfig:
    enablePrometheusMerge: true
    # Config for the default ProxyConfig.
    # Initially using directly the proxy metadata - can also be activated using annotations
    # on the pod. This is an unsupported low-level API, pending review and decisions on
    # enabling the feature. Enabling the DNS listener is safe - and allows further testing
    # and gradual adoption by setting capture only on specific workloads. It also allows
    # VMs to use other DNS options, like dnsmasq or unbound.

    # The namespace to treat as the administrative root namespace for Istio configuration.
    # When processing a leaf namespace Istio will search for declarations in that namespace first
    # and if none are found it will search in the root namespace. Any matching declaration found in the root namespace
    # is processed as if it were declared in the leaf namespace.

    rootNamespace: istio-system

    # The trust domain corresponds to the trust root of a system
    # Refer to https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md#21-trust-domain
    trustDomain: "cluster.local"

    # TODO: the intent is to eventually have this enabled by default when security is used.
    # It is not clear if user should normally need to configure - the metadata is typically
    # used as an escape and to control testing and rollout, but it is not intended as a long-term
    # stable API.

    # What we may configure in mesh config is the ".global" - and use of other suffixes.
    # No hurry to do this in 1.6, we're trying to prove the code.

istio-ingressgateway-enabled: false
istio-ingressgateway:
  name: istio-ingressgateway
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  service:
# For AWS ALB
#    annotations:
#      service.beta.kubernetes.io/aws-load-balancer-name: sample-ingress
#      service.beta.kubernetes.io/aws-load-balancer-type: "external"
#      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
#      #      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
#      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

istio-egressgateway-enabled: false
istio-egressgateway:
  name: istio-egressgateway
  labels:
    app: istio-egressgateway
    istio: egressgateway
  service:
    type: ClusterIP

istio-routing-setup:
  enabled: false

istio-observability-prometheus:
  enabled: false

istio-observability-kiali:
  enabled: false
