metadata:
  namespace: istio-network
spec:
  template:
    spec:
      serviceAccount: service-mesh-app-service1-serviceaccount
      containers:
        - env: # 環境変数設定
            - name: SERVICE_SERVICE2_URL
              value: "http://service-mesh-app-service2"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          imagePullPolicy: Always
