spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
#            authorizationUri: http://13.231.124.138:7000/auth/realms/master/protocol/openid-connect/auth
#            tokenUri: http://13.231.124.138:7000/auth/realms/master/protocol/openid-connect/token
#            userInfoUri: http://13.231.124.138:7000/auth/realms/master/protocol/openid-connect/userinfo
#            jwkSetUri: http://13.231.124.138:7000/auth/realms/master/protocol/openid-connect/certs
#            issuer-uri: http://13.231.124.138:7000/auth/realms/master
            authorizationUri: http://13.231.124.138:7000/realms/master/protocol/openid-connect/auth
            tokenUri: http://13.231.124.138:7000/realms/master/protocol/openid-connect/token
            userInfoUri: http://13.231.124.138:7000/realms/master/protocol/openid-connect/userinfo
            jwkSetUri: http://13.231.124.138:7000/realms/master/protocol/openid-connect/certs
            issuer-uri: http://13.231.124.138:7000/realms/master
        registration:
          keycloak:
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            clientId: service_mesh_app_local
            clientSecret: YEUWzr3g2eNvnFZwtoCTU3HlUt1EPFDZ
service:
  service1:
    dns: http://localhost:8081
  service2:
    dns: http://localhost:8082
