spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorizationUri: http://13.231.124.138:7000/realms/master/protocol/openid-connect/auth
            tokenUri: http://13.231.124.138:7000/realms/master/protocol/openid-connect/token
            userInfoUri: http://13.231.124.138:7000/realms/master/protocol/openid-connect/userinfo
            jwkSetUri: http://13.231.124.138:7000/realms/master/protocol/openid-connect/certs
            userNameAttribute: preferred_username
            issuer-uri: http://13.231.124.138:7000/realms/master
        registration:
          keycloak:
#            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
#            redirectUri: 'http://service-mesh-webapp/login/oauth2/code/keycloak'
            redirectUri: 'http://13.231.124.138:8090/login/oauth2/code/keycloak'
            clientId: service_mesh_app_dev
            clientSecret: ZqOrRS6Odgi2dytnHW3PhXeYcHmEMHTK
service:
  service1:
    url: http://service-mesh-app-service1.istio-network:8080
  service2:
    url: http://service-mesh-app-service2.istio-network:8080
